services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      BACKEND_URL: backend:8000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package-lock.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_URL: postgres://backend-local:password@db:5432/payment-manager?sslmode=disable
      GOOGLE_APPLICATION_CREDENTIALS: /application_default_credentials.json
      GOOGLE_CLOUD_QUOTA_PROJECT: payment-manager-stg
      PROJECT_ID: payment-manager-stg
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/application_default_credentials.json:ro

    develop:
      watch:
        - action: rebuild
          path: ./backend

  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: payment-manager
      POSTGRES_USER: backend-local
      POSTGRES_PASSWORD: password
