services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:8080
    environment:
      PORT: 8080
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package-lock.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:password@db:5432/postgres?sslmode=disable
    develop:
      watch:
        - action: rebuild
          path: ./backend

  db:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
