// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: proto/paymentcategory/v1/paymentcategory.proto

package paymentcategoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentCategoryService_FindPaymentCategoriesByUserId_FullMethodName = "/paymentcategory.v1.PaymentCategoryService/FindPaymentCategoriesByUserId"
)

// PaymentCategoryServiceClient is the client API for PaymentCategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentCategoryServiceClient interface {
	FindPaymentCategoriesByUserId(ctx context.Context, in *FindPaymentCategoriesByUserIdRequest, opts ...grpc.CallOption) (*FindPaymentCategoriesByUserIdResponse, error)
}

type paymentCategoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentCategoryServiceClient(cc grpc.ClientConnInterface) PaymentCategoryServiceClient {
	return &paymentCategoryServiceClient{cc}
}

func (c *paymentCategoryServiceClient) FindPaymentCategoriesByUserId(ctx context.Context, in *FindPaymentCategoriesByUserIdRequest, opts ...grpc.CallOption) (*FindPaymentCategoriesByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindPaymentCategoriesByUserIdResponse)
	err := c.cc.Invoke(ctx, PaymentCategoryService_FindPaymentCategoriesByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentCategoryServiceServer is the server API for PaymentCategoryService service.
// All implementations must embed UnimplementedPaymentCategoryServiceServer
// for forward compatibility.
type PaymentCategoryServiceServer interface {
	FindPaymentCategoriesByUserId(context.Context, *FindPaymentCategoriesByUserIdRequest) (*FindPaymentCategoriesByUserIdResponse, error)
	mustEmbedUnimplementedPaymentCategoryServiceServer()
}

// UnimplementedPaymentCategoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentCategoryServiceServer struct{}

func (UnimplementedPaymentCategoryServiceServer) FindPaymentCategoriesByUserId(context.Context, *FindPaymentCategoriesByUserIdRequest) (*FindPaymentCategoriesByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPaymentCategoriesByUserId not implemented")
}
func (UnimplementedPaymentCategoryServiceServer) mustEmbedUnimplementedPaymentCategoryServiceServer() {
}
func (UnimplementedPaymentCategoryServiceServer) testEmbeddedByValue() {}

// UnsafePaymentCategoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentCategoryServiceServer will
// result in compilation errors.
type UnsafePaymentCategoryServiceServer interface {
	mustEmbedUnimplementedPaymentCategoryServiceServer()
}

func RegisterPaymentCategoryServiceServer(s grpc.ServiceRegistrar, srv PaymentCategoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentCategoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentCategoryService_ServiceDesc, srv)
}

func _PaymentCategoryService_FindPaymentCategoriesByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPaymentCategoriesByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentCategoryServiceServer).FindPaymentCategoriesByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentCategoryService_FindPaymentCategoriesByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentCategoryServiceServer).FindPaymentCategoriesByUserId(ctx, req.(*FindPaymentCategoriesByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentCategoryService_ServiceDesc is the grpc.ServiceDesc for PaymentCategoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentCategoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentcategory.v1.PaymentCategoryService",
	HandlerType: (*PaymentCategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindPaymentCategoriesByUserId",
			Handler:    _PaymentCategoryService_FindPaymentCategoriesByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paymentcategory/v1/paymentcategory.proto",
}
