// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file common/apperror.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/apperror.proto.
 */
export const file_common_apperror: GenFile = /*@__PURE__*/
  fileDesc("ChVjb21tb24vYXBwZXJyb3IucHJvdG8SBmNvbW1vbiIpCghBcHBFcnJvchIMCgRjb2RlGAEgASgFEg8KB21lc3NhZ2UYAiABKAlCmQEKCmNvbS5jb21tb25CDUFwcGVycm9yUHJvdG9QAVpEZ2l0aHViLmNvbS9rYW5hcnUtc3NrL3BheW1lbnQtbWFuYWdlci9iYWNrZW5kL2ludGVyZmFjZS9wcm90by9jb21tb26iAgNDWFiqAgZDb21tb27KAgZDb21tb27iAhJDb21tb25cR1BCTWV0YWRhdGHqAgZDb21tb25iBnByb3RvMw");

/**
 * @generated from message common.AppError
 */
export type AppError = Message<"common.AppError"> & {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message common.AppError.
 * Use `create(AppErrorSchema)` to create a new message.
 */
export const AppErrorSchema: GenMessage<AppError> = /*@__PURE__*/
  messageDesc(file_common_apperror, 0);

