// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file paymentcategory/v1/paymentcategory.proto (package paymentcategory.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file paymentcategory/v1/paymentcategory.proto.
 */
export const file_paymentcategory_v1_paymentcategory: GenFile = /*@__PURE__*/
  fileDesc("CihwYXltZW50Y2F0ZWdvcnkvdjEvcGF5bWVudGNhdGVnb3J5LnByb3RvEhJwYXltZW50Y2F0ZWdvcnkudjEi+AEKD1BheW1lbnRDYXRlZ29yeRIbChNwYXltZW50X2NhdGVnb3J5X2lkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSHQoVcGF5bWVudF9jYXRlZ29yeV9uYW1lGAMgASgJEhAKCGlzX25lZWRzGAQgASgIEhIKCmNvbG9yX25hbWUYBSABKAkSEgoKY29sb3JfdG9uZRgGIAEoAxIuCgpjcmVhdGVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCI3CiRGaW5kUGF5bWVudENhdGVnb3JpZXNCeVVzZXJJZFJlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCSJoCiVGaW5kUGF5bWVudENhdGVnb3JpZXNCeVVzZXJJZFJlc3BvbnNlEj8KEnBheW1lbnRfY2F0ZWdvcmllcxgBIAMoCzIjLnBheW1lbnRjYXRlZ29yeS52MS5QYXltZW50Q2F0ZWdvcnkyrwEKFlBheW1lbnRDYXRlZ29yeVNlcnZpY2USlAEKHUZpbmRQYXltZW50Q2F0ZWdvcmllc0J5VXNlcklkEjgucGF5bWVudGNhdGVnb3J5LnYxLkZpbmRQYXltZW50Q2F0ZWdvcmllc0J5VXNlcklkUmVxdWVzdBo5LnBheW1lbnRjYXRlZ29yeS52MS5GaW5kUGF5bWVudENhdGVnb3JpZXNCeVVzZXJJZFJlc3BvbnNlQvsBChZjb20ucGF5bWVudGNhdGVnb3J5LnYxQhRQYXltZW50Y2F0ZWdvcnlQcm90b1ABWmJnaXRodWIuY29tL2thbmFydS1zc2svcGF5bWVudC1tYW5hZ2VyL2JhY2tlbmQvaW50ZXJmYWNlL3Byb3RvL3BheW1lbnRjYXRlZ29yeS92MTtwYXltZW50Y2F0ZWdvcnl2MaICA1BYWKoCElBheW1lbnRjYXRlZ29yeS5WMcoCElBheW1lbnRjYXRlZ29yeVxWMeICHlBheW1lbnRjYXRlZ29yeVxWMVxHUEJNZXRhZGF0YeoCE1BheW1lbnRjYXRlZ29yeTo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message paymentcategory.v1.PaymentCategory
 */
export type PaymentCategory = Message<"paymentcategory.v1.PaymentCategory"> & {
  /**
   * @generated from field: string payment_category_id = 1;
   */
  paymentCategoryId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string payment_category_name = 3;
   */
  paymentCategoryName: string;

  /**
   * @generated from field: bool is_needs = 4;
   */
  isNeeds: boolean;

  /**
   * @generated from field: string color_name = 5;
   */
  colorName: string;

  /**
   * @generated from field: int64 color_tone = 6;
   */
  colorTone: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message paymentcategory.v1.PaymentCategory.
 * Use `create(PaymentCategorySchema)` to create a new message.
 */
export const PaymentCategorySchema: GenMessage<PaymentCategory> = /*@__PURE__*/
  messageDesc(file_paymentcategory_v1_paymentcategory, 0);

/**
 * @generated from message paymentcategory.v1.FindPaymentCategoriesByUserIdRequest
 */
export type FindPaymentCategoriesByUserIdRequest = Message<"paymentcategory.v1.FindPaymentCategoriesByUserIdRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message paymentcategory.v1.FindPaymentCategoriesByUserIdRequest.
 * Use `create(FindPaymentCategoriesByUserIdRequestSchema)` to create a new message.
 */
export const FindPaymentCategoriesByUserIdRequestSchema: GenMessage<FindPaymentCategoriesByUserIdRequest> = /*@__PURE__*/
  messageDesc(file_paymentcategory_v1_paymentcategory, 1);

/**
 * @generated from message paymentcategory.v1.FindPaymentCategoriesByUserIdResponse
 */
export type FindPaymentCategoriesByUserIdResponse = Message<"paymentcategory.v1.FindPaymentCategoriesByUserIdResponse"> & {
  /**
   * @generated from field: repeated paymentcategory.v1.PaymentCategory payment_categories = 1;
   */
  paymentCategories: PaymentCategory[];
};

/**
 * Describes the message paymentcategory.v1.FindPaymentCategoriesByUserIdResponse.
 * Use `create(FindPaymentCategoriesByUserIdResponseSchema)` to create a new message.
 */
export const FindPaymentCategoriesByUserIdResponseSchema: GenMessage<FindPaymentCategoriesByUserIdResponse> = /*@__PURE__*/
  messageDesc(file_paymentcategory_v1_paymentcategory, 2);

/**
 * @generated from service paymentcategory.v1.PaymentCategoryService
 */
export const PaymentCategoryService: GenService<{
  /**
   * @generated from rpc paymentcategory.v1.PaymentCategoryService.FindPaymentCategoriesByUserId
   */
  findPaymentCategoriesByUserId: {
    methodKind: "unary";
    input: typeof FindPaymentCategoriesByUserIdRequestSchema;
    output: typeof FindPaymentCategoriesByUserIdResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_paymentcategory_v1_paymentcategory, 0);

