apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/payment-manager-prod/main/backend:${IMAGE_TAG}
          ports:
            - name: h2c
