apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-egress: all-traffic
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/network-interfaces: '[{"network":"vpc","subnetwork":"subnet-backend"}]'
    spec:
      serviceAccountName: backend@payment-manager-stg.iam.gserviceaccount.com
      containers:
        - image: asia-northeast1-docker.pkg.dev/payment-manager-stg/main/backend:${IMAGE_TAG}
          ports:
            - name: h2c
          env:
            - name: PROJECT_ID
              value: payment-manager-stg
            - name: FRONTEND_URL
              value: https://frontend-916038765681.asia-northeast1.run.app
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: DB_URL
                  key: latest
