// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Status } from "../../common/status_pb";
import { file_common_status } from "../../common/status_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiYgoEQXV0aBIPCgd1c2VyX2lkGAEgASgJEhEKCXVzZXJfbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIQCghpZF90b2tlbhgEIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAUgASgJIiYKFVNlbmRTaWduSW5MaW5rUmVxdWVzdBINCgVlbWFpbBgBIAEoCSI4ChZTZW5kU2lnbkluTGlua1Jlc3BvbnNlEh4KBnN0YXR1cxgBIAEoCzIOLmNvbW1vbi5TdGF0dXMiQgoVU2lnbkluV2l0aExpbmtSZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhoKEnZlcmlmaWNhdGlvbl90b2tlbhgCIAEoCSJVChZTaWduSW5XaXRoTGlua1Jlc3BvbnNlEh4KBnN0YXR1cxgBIAEoCzIOLmNvbW1vbi5TdGF0dXMSGwoEYXV0aBgCIAEoCzINLmF1dGgudjEuQXV0aCI+ChpTZW5kQ2hhbmdlRW1haWxMaW5rUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIRCgluZXdfZW1haWwYAiABKAkiPQobU2VuZENoYW5nZUVtYWlsTGlua1Jlc3BvbnNlEh4KBnN0YXR1cxgBIAEoCzIOLmNvbW1vbi5TdGF0dXMiRwoaQ2hhbmdlRW1haWxXaXRoTGlua1JlcXVlc3QSDQoFZW1haWwYASABKAkSGgoSdmVyaWZpY2F0aW9uX3Rva2VuGAIgASgJIj0KG0NoYW5nZUVtYWlsV2l0aExpbmtSZXNwb25zZRIeCgZzdGF0dXMYASABKAsyDi5jb21tb24uU3RhdHVzMvcCCgtBdXRoU2VydmljZRJRCg5TZW5kU2lnbkluTGluaxIeLmF1dGgudjEuU2VuZFNpZ25JbkxpbmtSZXF1ZXN0Gh8uYXV0aC52MS5TZW5kU2lnbkluTGlua1Jlc3BvbnNlElEKDlNpZ25JbldpdGhMaW5rEh4uYXV0aC52MS5TaWduSW5XaXRoTGlua1JlcXVlc3QaHy5hdXRoLnYxLlNpZ25JbldpdGhMaW5rUmVzcG9uc2USYAoTU2VuZENoYW5nZUVtYWlsTGluaxIjLmF1dGgudjEuU2VuZENoYW5nZUVtYWlsTGlua1JlcXVlc3QaJC5hdXRoLnYxLlNlbmRDaGFuZ2VFbWFpbExpbmtSZXNwb25zZRJgChNDaGFuZ2VFbWFpbFdpdGhMaW5rEiMuYXV0aC52MS5DaGFuZ2VFbWFpbFdpdGhMaW5rUmVxdWVzdBokLmF1dGgudjEuQ2hhbmdlRW1haWxXaXRoTGlua1Jlc3BvbnNlQqMBCgtjb20uYXV0aC52MUIJQXV0aFByb3RvUAFaTGdpdGh1Yi5jb20va2FuYXJ1LXNzay9wYXltZW50LW1hbmFnZXIvYmFja2VuZC9pbnRlcmZhY2UvcHJvdG8vYXV0aC92MTthdXRodjGiAgNBWFiqAgdBdXRoLlYxygIHQXV0aFxWMeICE0F1dGhcVjFcR1BCTWV0YWRhdGHqAghBdXRoOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp, file_common_status]);

/**
 * @generated from message auth.v1.Auth
 */
export type Auth = Message<"auth.v1.Auth"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string user_name = 2;
   */
  userName: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string id_token = 4;
   */
  idToken: string;

  /**
   * @generated from field: string refresh_token = 5;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.v1.Auth.
 * Use `create(AuthSchema)` to create a new message.
 */
export const AuthSchema: GenMessage<Auth> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * @generated from message auth.v1.SendSignInLinkRequest
 */
export type SendSignInLinkRequest = Message<"auth.v1.SendSignInLinkRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;
};

/**
 * Describes the message auth.v1.SendSignInLinkRequest.
 * Use `create(SendSignInLinkRequestSchema)` to create a new message.
 */
export const SendSignInLinkRequestSchema: GenMessage<SendSignInLinkRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * @generated from message auth.v1.SendSignInLinkResponse
 */
export type SendSignInLinkResponse = Message<"auth.v1.SendSignInLinkResponse"> & {
  /**
   * @generated from field: common.Status status = 1;
   */
  status?: Status;
};

/**
 * Describes the message auth.v1.SendSignInLinkResponse.
 * Use `create(SendSignInLinkResponseSchema)` to create a new message.
 */
export const SendSignInLinkResponseSchema: GenMessage<SendSignInLinkResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 2);

/**
 * @generated from message auth.v1.SignInWithLinkRequest
 */
export type SignInWithLinkRequest = Message<"auth.v1.SignInWithLinkRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string verification_token = 2;
   */
  verificationToken: string;
};

/**
 * Describes the message auth.v1.SignInWithLinkRequest.
 * Use `create(SignInWithLinkRequestSchema)` to create a new message.
 */
export const SignInWithLinkRequestSchema: GenMessage<SignInWithLinkRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 3);

/**
 * @generated from message auth.v1.SignInWithLinkResponse
 */
export type SignInWithLinkResponse = Message<"auth.v1.SignInWithLinkResponse"> & {
  /**
   * @generated from field: common.Status status = 1;
   */
  status?: Status;

  /**
   * @generated from field: auth.v1.Auth auth = 2;
   */
  auth?: Auth;
};

/**
 * Describes the message auth.v1.SignInWithLinkResponse.
 * Use `create(SignInWithLinkResponseSchema)` to create a new message.
 */
export const SignInWithLinkResponseSchema: GenMessage<SignInWithLinkResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 4);

/**
 * @generated from message auth.v1.SendChangeEmailLinkRequest
 */
export type SendChangeEmailLinkRequest = Message<"auth.v1.SendChangeEmailLinkRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string new_email = 2;
   */
  newEmail: string;
};

/**
 * Describes the message auth.v1.SendChangeEmailLinkRequest.
 * Use `create(SendChangeEmailLinkRequestSchema)` to create a new message.
 */
export const SendChangeEmailLinkRequestSchema: GenMessage<SendChangeEmailLinkRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 5);

/**
 * @generated from message auth.v1.SendChangeEmailLinkResponse
 */
export type SendChangeEmailLinkResponse = Message<"auth.v1.SendChangeEmailLinkResponse"> & {
  /**
   * @generated from field: common.Status status = 1;
   */
  status?: Status;
};

/**
 * Describes the message auth.v1.SendChangeEmailLinkResponse.
 * Use `create(SendChangeEmailLinkResponseSchema)` to create a new message.
 */
export const SendChangeEmailLinkResponseSchema: GenMessage<SendChangeEmailLinkResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 6);

/**
 * @generated from message auth.v1.ChangeEmailWithLinkRequest
 */
export type ChangeEmailWithLinkRequest = Message<"auth.v1.ChangeEmailWithLinkRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string verification_token = 2;
   */
  verificationToken: string;
};

/**
 * Describes the message auth.v1.ChangeEmailWithLinkRequest.
 * Use `create(ChangeEmailWithLinkRequestSchema)` to create a new message.
 */
export const ChangeEmailWithLinkRequestSchema: GenMessage<ChangeEmailWithLinkRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 7);

/**
 * @generated from message auth.v1.ChangeEmailWithLinkResponse
 */
export type ChangeEmailWithLinkResponse = Message<"auth.v1.ChangeEmailWithLinkResponse"> & {
  /**
   * @generated from field: common.Status status = 1;
   */
  status?: Status;
};

/**
 * Describes the message auth.v1.ChangeEmailWithLinkResponse.
 * Use `create(ChangeEmailWithLinkResponseSchema)` to create a new message.
 */
export const ChangeEmailWithLinkResponseSchema: GenMessage<ChangeEmailWithLinkResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 8);

/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.v1.AuthService.SendSignInLink
   */
  sendSignInLink: {
    methodKind: "unary";
    input: typeof SendSignInLinkRequestSchema;
    output: typeof SendSignInLinkResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.SignInWithLink
   */
  signInWithLink: {
    methodKind: "unary";
    input: typeof SignInWithLinkRequestSchema;
    output: typeof SignInWithLinkResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.SendChangeEmailLink
   */
  sendChangeEmailLink: {
    methodKind: "unary";
    input: typeof SendChangeEmailLinkRequestSchema;
    output: typeof SendChangeEmailLinkResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.ChangeEmailWithLink
   */
  changeEmailWithLink: {
    methodKind: "unary";
    input: typeof ChangeEmailWithLinkRequestSchema;
    output: typeof ChangeEmailWithLinkResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_v1_auth, 0);

