/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: google/cloud/identitytoolkit/v2/authentication_service.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../api/annotations";
import * as dependency_2 from "./../../../api/client";
import * as dependency_3 from "./../../../api/field_behavior";
import * as dependency_4 from "./mfa_info";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace google.cloud.identitytoolkit.v2 {
    export class FinalizeMfaSignInRequest extends pb_1.Message {
        #one_of_decls: number[][] = [[3]];
        constructor(data?: any[] | ({
            mfa_pending_credential?: string;
            tenant_id?: string;
        } & (({
            phone_verification_info?: dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneRequestInfo;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("mfa_pending_credential" in data && data.mfa_pending_credential != undefined) {
                    this.mfa_pending_credential = data.mfa_pending_credential;
                }
                if ("phone_verification_info" in data && data.phone_verification_info != undefined) {
                    this.phone_verification_info = data.phone_verification_info;
                }
                if ("tenant_id" in data && data.tenant_id != undefined) {
                    this.tenant_id = data.tenant_id;
                }
            }
        }
        get mfa_pending_credential() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set mfa_pending_credential(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get phone_verification_info() {
            return pb_1.Message.getWrapperField(this, dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneRequestInfo, 3) as dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneRequestInfo;
        }
        set phone_verification_info(value: dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneRequestInfo) {
            pb_1.Message.setOneofWrapperField(this, 3, this.#one_of_decls[0], value);
        }
        get has_phone_verification_info() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get tenant_id() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set tenant_id(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get verification_info() {
            const cases: {
                [index: number]: "none" | "phone_verification_info";
            } = {
                0: "none",
                3: "phone_verification_info"
            };
            return cases[pb_1.Message.computeOneofCase(this, [3])];
        }
        static fromObject(data: {
            mfa_pending_credential?: string;
            phone_verification_info?: ReturnType<typeof dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneRequestInfo.prototype.toObject>;
            tenant_id?: string;
        }): FinalizeMfaSignInRequest {
            const message = new FinalizeMfaSignInRequest({});
            if (data.mfa_pending_credential != null) {
                message.mfa_pending_credential = data.mfa_pending_credential;
            }
            if (data.phone_verification_info != null) {
                message.phone_verification_info = dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneRequestInfo.fromObject(data.phone_verification_info);
            }
            if (data.tenant_id != null) {
                message.tenant_id = data.tenant_id;
            }
            return message;
        }
        toObject() {
            const data: {
                mfa_pending_credential?: string;
                phone_verification_info?: ReturnType<typeof dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneRequestInfo.prototype.toObject>;
                tenant_id?: string;
            } = {};
            if (this.mfa_pending_credential != null) {
                data.mfa_pending_credential = this.mfa_pending_credential;
            }
            if (this.phone_verification_info != null) {
                data.phone_verification_info = this.phone_verification_info.toObject();
            }
            if (this.tenant_id != null) {
                data.tenant_id = this.tenant_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.mfa_pending_credential.length)
                writer.writeString(2, this.mfa_pending_credential);
            if (this.has_phone_verification_info)
                writer.writeMessage(3, this.phone_verification_info, () => this.phone_verification_info.serialize(writer));
            if (this.tenant_id.length)
                writer.writeString(4, this.tenant_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FinalizeMfaSignInRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FinalizeMfaSignInRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 2:
                        message.mfa_pending_credential = reader.readString();
                        break;
                    case 3:
                        reader.readMessage(message.phone_verification_info, () => message.phone_verification_info = dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneRequestInfo.deserialize(reader));
                        break;
                    case 4:
                        message.tenant_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FinalizeMfaSignInRequest {
            return FinalizeMfaSignInRequest.deserialize(bytes);
        }
    }
    export class FinalizeMfaSignInResponse extends pb_1.Message {
        #one_of_decls: number[][] = [[3]];
        constructor(data?: any[] | ({
            id_token?: string;
            refresh_token?: string;
        } & (({
            phone_auth_info?: dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneResponseInfo;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id_token" in data && data.id_token != undefined) {
                    this.id_token = data.id_token;
                }
                if ("refresh_token" in data && data.refresh_token != undefined) {
                    this.refresh_token = data.refresh_token;
                }
                if ("phone_auth_info" in data && data.phone_auth_info != undefined) {
                    this.phone_auth_info = data.phone_auth_info;
                }
            }
        }
        get id_token() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set id_token(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get refresh_token() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set refresh_token(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get phone_auth_info() {
            return pb_1.Message.getWrapperField(this, dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneResponseInfo, 3) as dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneResponseInfo;
        }
        set phone_auth_info(value: dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneResponseInfo) {
            pb_1.Message.setOneofWrapperField(this, 3, this.#one_of_decls[0], value);
        }
        get has_phone_auth_info() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get auxiliary_auth_info() {
            const cases: {
                [index: number]: "none" | "phone_auth_info";
            } = {
                0: "none",
                3: "phone_auth_info"
            };
            return cases[pb_1.Message.computeOneofCase(this, [3])];
        }
        static fromObject(data: {
            id_token?: string;
            refresh_token?: string;
            phone_auth_info?: ReturnType<typeof dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneResponseInfo.prototype.toObject>;
        }): FinalizeMfaSignInResponse {
            const message = new FinalizeMfaSignInResponse({});
            if (data.id_token != null) {
                message.id_token = data.id_token;
            }
            if (data.refresh_token != null) {
                message.refresh_token = data.refresh_token;
            }
            if (data.phone_auth_info != null) {
                message.phone_auth_info = dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneResponseInfo.fromObject(data.phone_auth_info);
            }
            return message;
        }
        toObject() {
            const data: {
                id_token?: string;
                refresh_token?: string;
                phone_auth_info?: ReturnType<typeof dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneResponseInfo.prototype.toObject>;
            } = {};
            if (this.id_token != null) {
                data.id_token = this.id_token;
            }
            if (this.refresh_token != null) {
                data.refresh_token = this.refresh_token;
            }
            if (this.phone_auth_info != null) {
                data.phone_auth_info = this.phone_auth_info.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id_token.length)
                writer.writeString(1, this.id_token);
            if (this.refresh_token.length)
                writer.writeString(2, this.refresh_token);
            if (this.has_phone_auth_info)
                writer.writeMessage(3, this.phone_auth_info, () => this.phone_auth_info.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FinalizeMfaSignInResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FinalizeMfaSignInResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id_token = reader.readString();
                        break;
                    case 2:
                        message.refresh_token = reader.readString();
                        break;
                    case 3:
                        reader.readMessage(message.phone_auth_info, () => message.phone_auth_info = dependency_4.google.cloud.identitytoolkit.v2.FinalizeMfaPhoneResponseInfo.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FinalizeMfaSignInResponse {
            return FinalizeMfaSignInResponse.deserialize(bytes);
        }
    }
    export class StartMfaSignInRequest extends pb_1.Message {
        #one_of_decls: number[][] = [[4]];
        constructor(data?: any[] | ({
            mfa_pending_credential?: string;
            mfa_enrollment_id?: string;
            tenant_id?: string;
        } & (({
            phone_sign_in_info?: dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneRequestInfo;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("mfa_pending_credential" in data && data.mfa_pending_credential != undefined) {
                    this.mfa_pending_credential = data.mfa_pending_credential;
                }
                if ("mfa_enrollment_id" in data && data.mfa_enrollment_id != undefined) {
                    this.mfa_enrollment_id = data.mfa_enrollment_id;
                }
                if ("phone_sign_in_info" in data && data.phone_sign_in_info != undefined) {
                    this.phone_sign_in_info = data.phone_sign_in_info;
                }
                if ("tenant_id" in data && data.tenant_id != undefined) {
                    this.tenant_id = data.tenant_id;
                }
            }
        }
        get mfa_pending_credential() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set mfa_pending_credential(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get mfa_enrollment_id() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set mfa_enrollment_id(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get phone_sign_in_info() {
            return pb_1.Message.getWrapperField(this, dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneRequestInfo, 4) as dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneRequestInfo;
        }
        set phone_sign_in_info(value: dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneRequestInfo) {
            pb_1.Message.setOneofWrapperField(this, 4, this.#one_of_decls[0], value);
        }
        get has_phone_sign_in_info() {
            return pb_1.Message.getField(this, 4) != null;
        }
        get tenant_id() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set tenant_id(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get sign_in_info() {
            const cases: {
                [index: number]: "none" | "phone_sign_in_info";
            } = {
                0: "none",
                4: "phone_sign_in_info"
            };
            return cases[pb_1.Message.computeOneofCase(this, [4])];
        }
        static fromObject(data: {
            mfa_pending_credential?: string;
            mfa_enrollment_id?: string;
            phone_sign_in_info?: ReturnType<typeof dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneRequestInfo.prototype.toObject>;
            tenant_id?: string;
        }): StartMfaSignInRequest {
            const message = new StartMfaSignInRequest({});
            if (data.mfa_pending_credential != null) {
                message.mfa_pending_credential = data.mfa_pending_credential;
            }
            if (data.mfa_enrollment_id != null) {
                message.mfa_enrollment_id = data.mfa_enrollment_id;
            }
            if (data.phone_sign_in_info != null) {
                message.phone_sign_in_info = dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneRequestInfo.fromObject(data.phone_sign_in_info);
            }
            if (data.tenant_id != null) {
                message.tenant_id = data.tenant_id;
            }
            return message;
        }
        toObject() {
            const data: {
                mfa_pending_credential?: string;
                mfa_enrollment_id?: string;
                phone_sign_in_info?: ReturnType<typeof dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneRequestInfo.prototype.toObject>;
                tenant_id?: string;
            } = {};
            if (this.mfa_pending_credential != null) {
                data.mfa_pending_credential = this.mfa_pending_credential;
            }
            if (this.mfa_enrollment_id != null) {
                data.mfa_enrollment_id = this.mfa_enrollment_id;
            }
            if (this.phone_sign_in_info != null) {
                data.phone_sign_in_info = this.phone_sign_in_info.toObject();
            }
            if (this.tenant_id != null) {
                data.tenant_id = this.tenant_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.mfa_pending_credential.length)
                writer.writeString(2, this.mfa_pending_credential);
            if (this.mfa_enrollment_id.length)
                writer.writeString(3, this.mfa_enrollment_id);
            if (this.has_phone_sign_in_info)
                writer.writeMessage(4, this.phone_sign_in_info, () => this.phone_sign_in_info.serialize(writer));
            if (this.tenant_id.length)
                writer.writeString(5, this.tenant_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): StartMfaSignInRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new StartMfaSignInRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 2:
                        message.mfa_pending_credential = reader.readString();
                        break;
                    case 3:
                        message.mfa_enrollment_id = reader.readString();
                        break;
                    case 4:
                        reader.readMessage(message.phone_sign_in_info, () => message.phone_sign_in_info = dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneRequestInfo.deserialize(reader));
                        break;
                    case 5:
                        message.tenant_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): StartMfaSignInRequest {
            return StartMfaSignInRequest.deserialize(bytes);
        }
    }
    export class StartMfaSignInResponse extends pb_1.Message {
        #one_of_decls: number[][] = [[1]];
        constructor(data?: any[] | ({} & (({
            phone_response_info?: dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneResponseInfo;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("phone_response_info" in data && data.phone_response_info != undefined) {
                    this.phone_response_info = data.phone_response_info;
                }
            }
        }
        get phone_response_info() {
            return pb_1.Message.getWrapperField(this, dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneResponseInfo, 1) as dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneResponseInfo;
        }
        set phone_response_info(value: dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneResponseInfo) {
            pb_1.Message.setOneofWrapperField(this, 1, this.#one_of_decls[0], value);
        }
        get has_phone_response_info() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get response_info() {
            const cases: {
                [index: number]: "none" | "phone_response_info";
            } = {
                0: "none",
                1: "phone_response_info"
            };
            return cases[pb_1.Message.computeOneofCase(this, [1])];
        }
        static fromObject(data: {
            phone_response_info?: ReturnType<typeof dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneResponseInfo.prototype.toObject>;
        }): StartMfaSignInResponse {
            const message = new StartMfaSignInResponse({});
            if (data.phone_response_info != null) {
                message.phone_response_info = dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneResponseInfo.fromObject(data.phone_response_info);
            }
            return message;
        }
        toObject() {
            const data: {
                phone_response_info?: ReturnType<typeof dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneResponseInfo.prototype.toObject>;
            } = {};
            if (this.phone_response_info != null) {
                data.phone_response_info = this.phone_response_info.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_phone_response_info)
                writer.writeMessage(1, this.phone_response_info, () => this.phone_response_info.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): StartMfaSignInResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new StartMfaSignInResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.phone_response_info, () => message.phone_response_info = dependency_4.google.cloud.identitytoolkit.v2.StartMfaPhoneResponseInfo.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): StartMfaSignInResponse {
            return StartMfaSignInResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedAuthenticationServiceService {
        static definition = {
            FinalizeMfaSignIn: {
                path: "/google.cloud.identitytoolkit.v2.AuthenticationService/FinalizeMfaSignIn",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: FinalizeMfaSignInRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => FinalizeMfaSignInRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: FinalizeMfaSignInResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => FinalizeMfaSignInResponse.deserialize(new Uint8Array(bytes))
            },
            StartMfaSignIn: {
                path: "/google.cloud.identitytoolkit.v2.AuthenticationService/StartMfaSignIn",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: StartMfaSignInRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => StartMfaSignInRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: StartMfaSignInResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => StartMfaSignInResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract FinalizeMfaSignIn(call: grpc_1.ServerUnaryCall<FinalizeMfaSignInRequest, FinalizeMfaSignInResponse>, callback: grpc_1.sendUnaryData<FinalizeMfaSignInResponse>): void;
        abstract StartMfaSignIn(call: grpc_1.ServerUnaryCall<StartMfaSignInRequest, StartMfaSignInResponse>, callback: grpc_1.sendUnaryData<StartMfaSignInResponse>): void;
    }
    export class AuthenticationServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedAuthenticationServiceService.definition, "AuthenticationService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        FinalizeMfaSignIn: GrpcUnaryServiceInterface<FinalizeMfaSignInRequest, FinalizeMfaSignInResponse> = (message: FinalizeMfaSignInRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<FinalizeMfaSignInResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<FinalizeMfaSignInResponse>, callback?: grpc_1.requestCallback<FinalizeMfaSignInResponse>): grpc_1.ClientUnaryCall => {
            return super.FinalizeMfaSignIn(message, metadata, options, callback);
        };
        StartMfaSignIn: GrpcUnaryServiceInterface<StartMfaSignInRequest, StartMfaSignInResponse> = (message: StartMfaSignInRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<StartMfaSignInResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<StartMfaSignInResponse>, callback?: grpc_1.requestCallback<StartMfaSignInResponse>): grpc_1.ClientUnaryCall => {
            return super.StartMfaSignIn(message, metadata, options, callback);
        };
    }
}
