apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-egress: all-traffic
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/network-interfaces: '[{"network":"vpc","subnetwork":"subnet-frontend"}]'
    spec:
      serviceAccountName: frontend@payment-manager-prod.iam.gserviceaccount.com
      containers:
        - image: asia-northeast1-docker.pkg.dev/payment-manager-prod/main/frontend:${IMAGE_TAG}
          env:
            - name: BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: BACKEND_URL
                  key: latest
