apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/payment-manager-stg/main/frontend:${IMAGE_TAG}
