name: Deploy dev

on:
  workflow_dispatch:
    inputs:
      context:
        type: string
        description: docker buildを実行するディレクトリ
        required: true
      service_name:
        type: string
        description: サービス名
        required: true
      service_account:
        type: string
        description: Cloud Run にデプロイするためのサービスアカウント
        required: true
      yaml_path:
        type: string
        description: Cloud Runの設定ファイルへのパス
        required: true
      image_tag:
        type: string
        description: デプロイするイメージタグ
        required: true

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  # イメージをビルドしてArtifact Registryにプッシュ
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Google Cloud との認証情報セットアップ
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/877995333513/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@common-payment-manager.iam.gserviceaccount.com

      # Artifact Registry へログイン
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # すでにimageが存在するか確認
      - name: Check Image exists
        id: check
        run: |
          if gcloud artifacts docker tags list asia-northeast1-docker.pkg.dev/common-payment-manager/main/${{ inputs.service_name }} --filter="tag:${{ github.sha }}" --format="value(tag)" | grep -q ${{ github.sha }}; then
            echo "Tag already exists."
            echo "already_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag does not exists."
            echo "already_exists=false" >> $GITHUB_OUTPUT
          fi

      # docker buildxを有効化
      - name: Set up Docker Buildx
        if: steps.check.outputs.already_exists == 'false'
        uses: docker/setup-buildx-action@v3

      # Docker イメージをビルド＆プッシュする
      - name: Build and push
        if: steps.check.outputs.already_exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          push: true
          tags: asia-northeast1-docker.pkg.dev/common-payment-manager/main/${{ inputs.service_name }}:${{ github.sha }}

  # イメージを Cloud Run にデプロイ
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Google Cloud との認証情報セットアップ
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/877995333513/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: ${{ inputs.service_account }}

      # yaml 内のイメージタグを書き換える
      - name: Replace image tag
        run: |-
          envsubst < ${{ inputs.yaml_path }} > service.yaml
          cat service.yaml
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}

      # イメージを Cloud Run にデプロイする
      - name: Deploy
        run: gcloud run services replace service.yaml --region asia-northeast1
