name: Docker build & Push to Artifact Registry & Deploy to Cloud Run

on:
  workflow_call:
    inputs:
      env:
        type: choice
        required: true
        description: デプロイ先
        default: dev
        options:
          - dev
          - prd
      yaml_path:
        type: string
        description: Cloud Runの設定ファイルへのパス
        required: true
      image_tag:
        type: string
        description: デプロイするイメージタグ
        required: true

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Google Cloud との認証情報セットアップ
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/877995333513/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@${{ inputs.env }}-payment-manager.iam.gserviceaccount.com

      # yaml 内のイメージタグを書き換える
      - name: Replace image tag
        run: |-
          envsubst < ${{ inputs.yaml_path }} > service.yaml
          cat service.yaml
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}

      # イメージを Cloud Run にデプロイする
      - name: Deploy
        run: gcloud run services replace service.yaml --region asia-northeast1
