name: Deploy backend to dev

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

# 連続実行時に既に実行中のジョブを停止する
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
      cancel-in-progress: true

    name: Build backend
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      context: ./backend

  deploy:
    needs: build-push
    name: Deploy backend to dev
    uses: ./.github/workflows/deploy-cloud-run.yaml
    with:
      service_name: dev-payment-manager-backend
      yaml_path: ./backend/.infra/grpc-server/dev.yaml
      image_tag: ${{ github.sha }}
