name: Deploy Dispatcher

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: デプロイ先
        default: dev
        options:
          - dev
          - prd

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  backend-deploy:
    needs: project-info
    name: backend Deploy
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      env: ${{ inputs.env }}
      context: ./backend
      service_name: payment-manager-backend
      yaml_path: ./backend/.infra/grpc-server/${{ inputs.env }}.yaml
      image_tag: ${{ github.sha }}

  frontend-deploy:
    needs: project-info # SSGする場合はbackendデプロイ後にbuildするためにbackend-deployを追加
    name: frontend Deploy
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      env: ${{ inputs.env }}
      context: ./frontend
      service_name: payment-manager-frontend
      yaml_path: ./frontend/.infra/${{ inputs.env }}.yaml
      image_tag: ${{ github.sha }}
