name: Deploy Dispatcher

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: デプロイ先
        default: dev
        options:
          - dev
          - prd

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  project-info:
    runs-on: ubuntu-latest
    outputs:
      project_id: ${{ steps.echo.outputs.project_id }}
      project_number: ${{ steps.echo.outputs.project_number }}
    steps:
      - name: Set Project Info
        id: echo
        run: |
          if ${{ inputs.env == 'dev' }}; then
            echo "project_id=dev-payment-manager" >> "$GITHUB_OUTPUT"
            echo "project_number=604586293033" >> "$GITHUB_OUTPUT"
          else
            echo "project_id=prd-payment-manager" >> "$GITHUB_OUTPUT"
            echo "project_number=811083787873" >> "$GITHUB_OUTPUT"
          fi

  backend-build-push:
    needs: project-info
    name: backend Build & Push
    uses: ./.github/workflows/reusable-build-push.yaml
    with:
      project_id: ${{ needs.project-info.outputs.project_id }}
      project_number: ${{ needs.project-info.outputs.project_number }}
      context: ./backend
      service_name: payment-manager-backend

  backend-deploy:
    needs: [project-info, backend-build-push]
    name: backend Deploy
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      project_id: ${{ needs.project-info.outputs.project_id }}
      project_number: ${{ needs.project-info.outputs.project_number }}
      yaml_path: ./backend/.infra/grpc-server/dev.yaml
      image_tag: ${{ github.sha }}

  frontend-build-push:
    needs: project-info # SSGする場合はbackendデプロイ後にbuildするためにbackend-deployを追加
    name: frontend Build & Push
    uses: ./.github/workflows/reusable-build-push.yaml
    with:
      project_id: ${{ needs.project-info.outputs.project_id }}
      project_number: ${{ needs.project-info.outputs.project_number }}
      context: ./frontend
      service_name: payment-manager-frontend

  frontend-deploy:
    needs: [project-info, frontend-build-push]
    name: frontend Deploy
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      project_id: ${{ needs.project-info.outputs.project_id }}
      project_number: ${{ needs.project-info.outputs.project_number }}
      yaml_path: ./frontend/.infra/dev.yaml
      image_tag: ${{ github.sha }}
