name: Deploy dev

on: workflow_dispatch

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    strategy:
      matrix:
        yaml_path:
          [
            "./backend/.infra/grpc-server/dev.yaml",
            "./frontend/.infra/dev.yaml",
          ]
    name: Deploy
    uses: ./.github/workflows/deploy-cloud-run.yaml
    with:
      service_account: github-actions@dev-payment-manager.iam.gserviceaccount.com
      yaml_path: ${{ matrix.yaml_path }}
      image_tag: ${{ github.sha }}
