name: Deploy Dispatcher

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: デプロイ先
        default: stg
        options:
          - prod
          - stg

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  backend-deploy:
    name: backend Deploy
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      env: ${{ inputs.env }}
      context: ./backend
      service_name: backend
      yaml_path: ./backend/.infra/grpc-server/${{ inputs.env }}.yaml
      image_tag: ${{ github.sha }}

  frontend-deploy:
    # needs: backend-deploy # SSGする場合はbackendデプロイ後にbuildする
    name: frontend Deploy
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      env: ${{ inputs.env }}
      context: ./frontend
      service_name: frontend
      yaml_path: ./frontend/.infra/${{ inputs.env }}.yaml
      image_tag: ${{ github.sha }}
