name: Deploy dev

on: workflow_dispatch

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  build-push-deploy:
    name: Docker build & Push to Artifact Registry
    strategy:
      matrix:
        include:
          - context: ./backend
            service_name: payment-manager-backend
            yaml_path: ./backend/.infra/grpc-server/dev.yaml
          - context: ./frontend
            service_name: payment-manager-frontend
            yaml_path: ./frontend/.infra/dev.yaml
    uses: ./.github/workflows/build-push-deploy.yaml
    with:
      context: ${{ matrix.context }}
      service_name: ${{ matrix.service_name }}
      service_account: github-actions@dev-payment-manager.iam.gserviceaccount.com
      yaml_path: ${{ matrix.yaml_path }}
      image_tag: ${{ github.sha }}
