name: Deploy to Cloud Run

on: workflow_dispatch

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-cloud-run.yaml
    with:
      service_account: github-actions@dev-payment-manager.iam.gserviceaccount.com
      yaml_path: ./backend/.infra/grpc-server/dev.yaml
      image_tag: ${{ github.sha }}
      service_name: dev-payment-manager-backend
