# see: https://cloud.google.com/blog/ja/products/devops-sre/deploy-to-cloud-run-with-github-actions/
name: Deploy to Cloud Run

on:
  workflow_call:
    inputs:
      service_account:
        type: string
        description: Cloud Run にデプロイするためのサービスアカウント
        required: true
      yaml_path:
        type: string
        description: Cloud Runの設定ファイルへのパス
        required: true
      image_tag:
        type: string
        description: デプロイするイメージタグ
        required: true
      service_name:
        type: string
        description: Cloud Runのサービス名
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Google Cloud との認証情報セットアップ
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/877995333513/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: ${{ inputs.service_account }}

      # yaml 内のイメージタグを書き換える
      - name: Replace image tag
        run: |-
          envsubst < ${{ inputs.yaml_path }} > service.yaml
          cat service.yaml
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}

      # イメージを Cloud Run にデプロイする
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ inputs.service_name }}
          metadata: service.yaml
