name: Deploy backend to dev

on: workflow_dispatch

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    name: Deploy backend
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      context: ./backend
