name: Docker build & push

on:
  workflow_call:
    inputs:
      context:
        type: string
        description: docker buildを実行するディレクトリ
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Google Cloud との認証情報セットアップ
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/877995333513/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@common-payment-manager.iam.gserviceaccount.com

      # Artifact Registry へログイン
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # docker buildxを有効化
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker イメージをビルド＆プッシュする
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          push: true
          tags: asia-northeast1-docker.pkg.dev/common-payment-manager/main/payment-manager-backend:${{ github.sha }}
