name: Push main

on:
  push:
    branches:
      - main

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  build-push:
    name: Build backend
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      context: ./backend
