name: Push main

on:
  push:
    branches:
      - main

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  build-push:
    strategy:
      matrix:
        context: ["./backend/", "./frontend"]
    name: Docker build & Push to Artifact Registry
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      context: ${{ matrix.context }}
