name: Push main

on:
  push:
    branches:
      - main

# Google Cloud と OIDC 連携するために id-token: write 権限が必要
permissions:
  contents: read
  id-token: write

jobs:
  build-push:
    strategy:
      matrix:
        include:
          - context: ./backend
            service_name: payment-manager-backend
          - context: ./frontend
            service_name: payment-manager-frontend
    name: Docker build & Push to Artifact Registry
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      context: ${{ matrix.context }}
      service_name: ${{ matrix.service_name }}
