name: Deploy to Cloud Run

on:
  workflow_call:
    inputs:
      project_id:
        type: string
        description: Google Cloud Project ID
        required: true
      project_number:
        type: string
        description: Google Cloud Project Number
        required: true
      yaml_path:
        type: string
        description: Cloud Runの設定ファイルへのパス
        required: true
      image_tag:
        type: string
        description: デプロイするイメージタグ
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Google Cloud との認証情報セットアップ
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/${{ inputs.project_number }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@${{ inputs.project_id }}.iam.gserviceaccount.com

      # yaml 内のイメージタグを書き換える
      - name: Replace image tag
        run: |-
          envsubst < ${{ inputs.yaml_path }} > service.yaml
          cat service.yaml
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}

      # イメージを Cloud Run にデプロイする
      - name: Deploy
        run: gcloud run services replace service.yaml --region asia-northeast1
